name: h3php
build-mode: bin
version: 0.1.0
cxx-std: c++17
cxx-flags: |
  -framework Metal
  -framework MetalKit
  -framework Foundation
  -framework Accelerate
  -Imetal-cpp-main
  -Ivendor/swoole/phpx/include
  -I/opt/homebrew/opt/php@8.4/include/php
  -I/opt/homebrew/opt/php@8.4/include/php/main
  -I/opt/homebrew/opt/php@8.4/include/php/Zend
  -I/opt/homebrew/opt/php@8.4/include/php/TSRM
  -I/opt/homebrew/opt/php@8.4/include/php/ext
  -I/opt/homebrew/opt/php@8.4/include/php/ext/date/lib
ld-flags: |
  -framework Metal
  -framework MetalKit
  -framework Foundation
  -framework Accelerate
  -framework MetalPerformanceShaders
  -framework MetalPerformanceShadersGraph
  -licucore
  -L/Volumes/data/git/c/h3.c
  -lh3
  cpp-src/metal_native.o
  cpp-src/h3_native.o
sources:
  - php-src
ignore:
  - ./php-src/Testing
